import { Pressable, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';

import { AppText, FavoriteIcon, RatingBadge, RemoteImage } from '@/components/ui/app-ui';
import { colors, radii, spacing } from '@/constants/theme';
import type { Category, Establishment, Product, UserProductEntry } from '@/types/domain';

export function ProductCard({ product, entry, compact = false }: { product: Product; entry?: UserProductEntry; compact?: boolean }) { return <Pressable accessibilityLabel={`${product.name}, valoración ${entry?.rating ?? 0}`} onPress={() => router.push(`/products/${product.id}`)} style={[styles.product, compact && styles.compact]}><RemoteImage uri={product.coverImageUri} style={styles.fill} /><View style={styles.scrim} /><AppText variant="label" style={styles.name} numberOfLines={2}>{product.name}</AppText>{entry?.isFavorite && <View style={styles.favorite}><FavoriteIcon active /></View>}{entry && <RatingBadge value={entry.rating} />}</Pressable>; }
export function EstablishmentCard({ establishment }: { establishment: Establishment }) { return <Pressable onPress={() => router.push(`/establishments/${establishment.id}`)} style={styles.establishment}><RemoteImage uri={establishment.coverImageUri} style={styles.fill} /><View style={styles.scrim} /><AppText variant="label" style={styles.name}>{establishment.name}</AppText></Pressable>; }
export function CategoryCard({ category, count }: { category: Category; count?: number }) { return <Pressable onPress={() => router.push(`/categories/${category.id}`)} style={styles.category}><View><AppText variant="label">{category.name}</AppText><AppText variant="small" color={colors.textSecondary}>{count ?? 0} productos</AppText></View><AppText color={colors.accent}>›</AppText></Pressable>; }
const styles=StyleSheet.create({product:{width:164,aspectRatio:1,borderRadius:radii.image,overflow:'hidden',backgroundColor:colors.surfaceCard},compact:{width:'48%'},establishment:{width:176,height:132,borderRadius:radii.image,overflow:'hidden',backgroundColor:colors.surfaceCard},fill:{width:'100%',height:'100%'},scrim:{...StyleSheet.absoluteFillObject,backgroundColor:colors.imageScrim},name:{position:'absolute',left:spacing[8],right:spacing[8],bottom:spacing[8],paddingRight:48,textShadowColor:colors.onAccent,textShadowRadius:4},favorite:{position:'absolute',top:spacing[8],right:spacing[8],backgroundColor:colors.imageBadge,borderRadius:radii.pill,padding:spacing[4]},category:{minHeight:64,borderBottomWidth:1,borderBottomColor:colors.border,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingVertical:spacing[12]}});
