import { ScrollView, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { ProductCard, EstablishmentCard } from '@/components/cards/cards';
import { AppText, EmptyState, ErrorState, LoadingState, RemoteImage, Screen, SectionHeader } from '@/components/ui/app-ui';
import { colors, radii, spacing } from '@/constants/theme';
import { useAppData } from '@/providers/app-data-provider';

export default function HomeScreen(){const {data,loading,error,retry}=useAppData();if(loading)return <Screen><LoadingState/></Screen>;if(error||!data)return <Screen><ErrorState retry={retry}/></Screen>;const recent=[...data.products].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const favorites=recent.filter(p=>data.entries.find(e=>e.productId===p.id)?.isFavorite);return <Screen><View style={styles.top}><View><AppText color={colors.textSecondary}>Buenas tardes, {data.profile.displayName}</AppText><AppText variant="screen">Tasted</AppText></View><RemoteImage uri={data.profile.avatarUri} style={styles.avatar}/></View><SectionHeader title="Establecimientos recientes" action="Ver todos" onAction={()=>router.push('/search')}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.row}>{data.establishments.map(e=><EstablishmentCard key={e.id} establishment={e}/>)}</ScrollView><SectionHeader title="Añadidos recientemente"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.row}>{recent.map(p=><ProductCard key={p.id} product={p} entry={data.entries.find(e=>e.productId===p.id)}/>)}</ScrollView><SectionHeader title="Tus favoritos"/>{favorites.length?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.row}>{favorites.map(p=><ProductCard key={p.id} product={p} entry={data.entries.find(e=>e.productId===p.id)}/>)}</ScrollView>:<EmptyState title="Aún no hay favoritos" message="Marca los productos que quieras volver a encontrar."/>}</Screen>}
const styles=StyleSheet.create({top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},avatar:{width:52,height:52,borderRadius:radii.pill},row:{gap:spacing[12],paddingRight:spacing[20]}});
