create type public.establishment_type as enum ('supermarket','restaurant','cafe','ice_cream_shop','bakery','bar','food_shop','other');
create type public.entry_visibility as enum ('private','public');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text not null unique,display_name text not null,avatar_path text,bio text check(char_length(bio)<=500),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.establishments(id uuid primary key default gen_random_uuid(),created_by uuid not null references auth.users(id),name text not null check(char_length(trim(name))>0),normalized_name text not null,type public.establishment_type not null,description text,location_text text,city text,country_code text,website text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.establishment_images(id uuid primary key default gen_random_uuid(),establishment_id uuid not null references public.establishments(id) on delete cascade,uploaded_by uuid not null references auth.users(id),storage_path text not null unique,is_cover boolean not null default false,position integer not null default 0 check(position>=0),created_at timestamptz not null default now());
create unique index establishment_one_cover on public.establishment_images(establishment_id) where is_cover;
create table public.products(id uuid primary key default gen_random_uuid(),created_by uuid not null references auth.users(id),establishment_id uuid not null references public.establishments(id),name text not null check(char_length(trim(name))>0),normalized_name text not null,brand text,normalized_brand text,description text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index products_duplicate_lookup on public.products(establishment_id,normalized_name,normalized_brand);
create table public.product_images(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id) on delete cascade,uploaded_by uuid not null references auth.users(id),storage_path text not null unique,is_cover boolean not null default false,position integer not null default 0 check(position>=0),created_at timestamptz not null default now());
create unique index product_one_cover on public.product_images(product_id) where is_cover;
create table public.user_product_entries(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,product_id uuid not null references public.products(id),rating numeric(2,1) not null check(rating between 0.5 and 5 and rating*2=trunc(rating*2)),review_text text,is_favorite boolean not null default false,price_paid numeric(10,2) check(price_paid is null or price_paid>=0),currency_code text not null default 'EUR' check(char_length(currency_code)=3),tried_at date,visibility public.entry_visibility not null default 'private',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,product_id));
create index entries_user_recent on public.user_product_entries(user_id,created_at desc);create index entries_user_rating on public.user_product_entries(user_id,rating desc);create index entries_product on public.user_product_entries(product_id);create index entries_favorites on public.user_product_entries(user_id) where is_favorite;
create table public.categories(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,parent_id uuid references public.categories(id) on delete restrict,name text not null check(char_length(trim(name))>0),normalized_name text not null,description text,image_path text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(parent_id is null or parent_id<>id));
create unique index categories_root_name on public.categories(user_id,normalized_name) where parent_id is null;create unique index categories_sibling_name on public.categories(user_id,parent_id,normalized_name) where parent_id is not null;
create table public.entry_categories(entry_id uuid not null references public.user_product_entries(id) on delete cascade,category_id uuid not null references public.categories(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now(),primary key(entry_id,category_id));

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();return new;end$$;
create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at();create trigger establishments_updated before update on public.establishments for each row execute function public.set_updated_at();create trigger products_updated before update on public.products for each row execute function public.set_updated_at();create trigger entries_updated before update on public.user_product_entries for each row execute function public.set_updated_at();create trigger categories_updated before update on public.categories for each row execute function public.set_updated_at();

create or replace function public.create_profile_for_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,username,display_name) values(new.id,coalesce(nullif(lower(new.raw_user_meta_data->>'username'),''),'user_'||substr(new.id::text,1,8)),coalesce(nullif(new.raw_user_meta_data->>'display_name',''),'Tasted user'));return new;end$$;
create trigger auth_user_profile after insert on auth.users for each row execute function public.create_profile_for_user();

create or replace function public.validate_category_tree() returns trigger language plpgsql set search_path='' as $$declare owner uuid;cycle_found boolean;begin if new.parent_id is null then return new;end if;select user_id into owner from public.categories where id=new.parent_id;if owner is distinct from new.user_id then raise exception 'La categoría padre no pertenece al usuario';end if;with recursive ancestors as(select id,parent_id from public.categories where id=new.parent_id union all select c.id,c.parent_id from public.categories c join ancestors a on c.id=a.parent_id) select exists(select 1 from ancestors where id=new.id) into cycle_found;if cycle_found then raise exception 'La jerarquía produciría un ciclo';end if;return new;end$$;
create trigger categories_tree before insert or update of parent_id,user_id on public.categories for each row execute function public.validate_category_tree();
create or replace function public.validate_entry_category_owner() returns trigger language plpgsql set search_path='' as $$begin if not exists(select 1 from public.user_product_entries e where e.id=new.entry_id and e.user_id=new.user_id) or not exists(select 1 from public.categories c where c.id=new.category_id and c.user_id=new.user_id) then raise exception 'Entrada y categoría deben pertenecer al usuario';end if;return new;end$$;
create trigger entry_category_owner before insert or update on public.entry_categories for each row execute function public.validate_entry_category_owner();

alter table public.profiles enable row level security;alter table public.establishments enable row level security;alter table public.establishment_images enable row level security;alter table public.products enable row level security;alter table public.product_images enable row level security;alter table public.user_product_entries enable row level security;alter table public.categories enable row level security;alter table public.entry_categories enable row level security;
create policy profiles_select_own on public.profiles for select using(id=auth.uid());create policy profiles_update_own on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy establishments_read on public.establishments for select to authenticated using(true);create policy establishments_insert on public.establishments for insert to authenticated with check(created_by=auth.uid());create policy establishments_update_creator on public.establishments for update to authenticated using(created_by=auth.uid()) with check(created_by=auth.uid());
create policy establishment_images_read on public.establishment_images for select to authenticated using(true);create policy establishment_images_insert on public.establishment_images for insert to authenticated with check(uploaded_by=auth.uid() and exists(select 1 from public.establishments e where e.id=establishment_id and e.created_by=auth.uid()));create policy establishment_images_update on public.establishment_images for update to authenticated using(uploaded_by=auth.uid()) with check(uploaded_by=auth.uid());create policy establishment_images_delete on public.establishment_images for delete to authenticated using(uploaded_by=auth.uid());
create policy products_read on public.products for select to authenticated using(true);create policy products_insert on public.products for insert to authenticated with check(created_by=auth.uid());create policy products_update_creator on public.products for update to authenticated using(created_by=auth.uid()) with check(created_by=auth.uid());
create policy product_images_read on public.product_images for select to authenticated using(true);create policy product_images_insert on public.product_images for insert to authenticated with check(uploaded_by=auth.uid() and exists(select 1 from public.products p where p.id=product_id and p.created_by=auth.uid()));create policy product_images_update on public.product_images for update to authenticated using(uploaded_by=auth.uid()) with check(uploaded_by=auth.uid());create policy product_images_delete on public.product_images for delete to authenticated using(uploaded_by=auth.uid());
create policy entries_owner_all on public.user_product_entries for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());create policy categories_owner_all on public.categories for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());create policy entry_categories_owner_all on public.entry_categories for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

create or replace function public.save_product_with_entry(payload jsonb) returns table(product_id uuid,entry_id uuid) language plpgsql security definer set search_path='' as $$declare uid uuid:=auth.uid();pid uuid;eid uuid;cat text;created_product boolean:=false;begin if uid is null then raise exception 'Autenticación requerida';end if;if (payload->>'rating')::numeric not between 0.5 and 5 then raise exception 'Valoración inválida';end if;pid=nullif(payload->>'id','')::uuid;if pid is null then select p.id into pid from public.products p where p.establishment_id=(payload->>'establishment_id')::uuid and p.normalized_name=payload->>'normalized_name' and coalesce(p.normalized_brand,'')=coalesce(payload->>'normalized_brand','') limit 1;end if;if pid is null then insert into public.products(created_by,establishment_id,name,normalized_name,brand,normalized_brand,description) values(uid,(payload->>'establishment_id')::uuid,payload->>'name',payload->>'normalized_name',nullif(payload->>'brand',''),nullif(payload->>'normalized_brand',''),nullif(payload->>'description','')) returning id into pid;created_product=true;elsif payload->>'id' is not null and exists(select 1 from public.products where id=pid and created_by=uid) then update public.products set establishment_id=(payload->>'establishment_id')::uuid,name=payload->>'name',normalized_name=payload->>'normalized_name',brand=nullif(payload->>'brand',''),normalized_brand=nullif(payload->>'normalized_brand',''),description=nullif(payload->>'description','') where id=pid and created_by=uid;end if;insert into public.user_product_entries(user_id,product_id,rating,review_text,is_favorite,price_paid,currency_code,tried_at,visibility) values(uid,pid,(payload->>'rating')::numeric,nullif(payload->>'review_text',''),coalesce((payload->>'is_favorite')::boolean,false),nullif(payload->>'price_paid','')::numeric,coalesce(payload->>'currency_code','EUR'),nullif(payload->>'tried_at','')::date,'private') on conflict(user_id,product_id) do update set rating=excluded.rating,review_text=excluded.review_text,is_favorite=excluded.is_favorite,price_paid=excluded.price_paid,currency_code=excluded.currency_code,tried_at=excluded.tried_at returning id into eid;delete from public.entry_categories where entry_id=eid;for cat in select jsonb_array_elements_text(coalesce(payload->'category_ids','[]'::jsonb)) loop insert into public.entry_categories(entry_id,category_id,user_id) select eid,cat::uuid,uid from public.categories where id=cat::uuid and user_id=uid;if not found then raise exception 'Categoría no válida';end if;end loop;return query select pid,eid;exception when others then if created_product then delete from public.products where id=pid and not exists(select 1 from public.user_product_entries where product_id=pid);end if;raise;end$$;
create or replace function public.remove_product_from_diary(target_product_id uuid) returns void language plpgsql security definer set search_path='' as $$begin if auth.uid() is null then raise exception 'Autenticación requerida';end if;delete from public.user_product_entries where user_id=auth.uid() and product_id=target_product_id;end$$;
create or replace function public.delete_product_if_unused(target_product_id uuid) returns void language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.products where id=target_product_id and created_by=auth.uid()) then raise exception 'No autorizado';end if;if exists(select 1 from public.user_product_entries where product_id=target_product_id and user_id<>auth.uid()) then raise exception 'Otro usuario depende del producto';end if;delete from public.user_product_entries where product_id=target_product_id and user_id=auth.uid();delete from public.products where id=target_product_id;end$$;
create or replace function public.delete_establishment_if_empty(target_establishment_id uuid) returns void language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.establishments where id=target_establishment_id and created_by=auth.uid()) then raise exception 'No autorizado';end if;if exists(select 1 from public.products where establishment_id=target_establishment_id) then raise exception 'El establecimiento todavía tiene productos';end if;delete from public.establishments where id=target_establishment_id;end$$;
create or replace function public.delete_category_safe(target_category_id uuid) returns void language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.categories where id=target_category_id and user_id=auth.uid()) then raise exception 'No autorizado';end if;if exists(select 1 from public.categories where parent_id=target_category_id) then raise exception 'La categoría tiene subcategorías';end if;delete from public.categories where id=target_category_id and user_id=auth.uid();end$$;
create or replace function public.prepare_establishment_delete(target_establishment_id uuid) returns text[] language plpgsql security definer set search_path='' as $$declare paths text[];begin if not exists(select 1 from public.establishments where id=target_establishment_id and created_by=auth.uid()) then raise exception 'No autorizado';end if;if exists(select 1 from public.products where establishment_id=target_establishment_id) then raise exception 'El establecimiento todavía tiene productos';end if;select coalesce(array_agg(storage_path),array[]::text[]) into paths from public.establishment_images where establishment_id=target_establishment_id;return paths;end$$;
create or replace function public.prepare_category_delete(target_category_id uuid) returns text[] language plpgsql security definer set search_path='' as $$declare paths text[];begin if not exists(select 1 from public.categories where id=target_category_id and user_id=auth.uid()) then raise exception 'No autorizado';end if;if exists(select 1 from public.categories where parent_id=target_category_id) then raise exception 'La categoría tiene subcategorías';end if;select case when image_path is null then array[]::text[] else array[image_path] end into paths from public.categories where id=target_category_id;return paths;end$$;
revoke all on function public.save_product_with_entry(jsonb),public.remove_product_from_diary(uuid),public.delete_product_if_unused(uuid),public.delete_establishment_if_empty(uuid),public.delete_category_safe(uuid),public.prepare_establishment_delete(uuid),public.prepare_category_delete(uuid) from public;grant execute on function public.save_product_with_entry(jsonb),public.remove_product_from_diary(uuid),public.delete_product_if_unused(uuid),public.delete_establishment_if_empty(uuid),public.delete_category_safe(uuid),public.prepare_establishment_delete(uuid),public.prepare_category_delete(uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('avatars','avatars',true,5242880,array['image/jpeg','image/png','image/webp']),('establishment-images','establishment-images',true,10485760,array['image/jpeg','image/png','image/webp']),('product-images','product-images',true,10485760,array['image/jpeg','image/png','image/webp']),('category-images','category-images',true,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy storage_public_read on storage.objects for select using(bucket_id in('avatars','establishment-images','product-images','category-images'));
create policy storage_owner_insert on storage.objects for insert to authenticated with check(bucket_id in('avatars','establishment-images','product-images','category-images') and (storage.foldername(name))[1]=auth.uid()::text);
create policy storage_owner_update on storage.objects for update to authenticated using(bucket_id in('avatars','establishment-images','product-images','category-images') and (storage.foldername(name))[1]=auth.uid()::text) with check((storage.foldername(name))[1]=auth.uid()::text);
create policy storage_owner_delete on storage.objects for delete to authenticated using(bucket_id in('avatars','establishment-images','product-images','category-images') and (storage.foldername(name))[1]=auth.uid()::text);
